# Generated by Django 4.0.3 on 2022-04-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('amount_due', models.FloatField()),
                ('dob', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
